### ISSUE TITLE
Add suport to "--preserve" parameter

### ISSUE THREAD

**Issue by FABH** [sonatype/install4j-support#24]
This parameter is used to keep the temporary files created by Install4j.
This option is not showed in --help, but its mentioned in http://stackoverflow.com/a/32273724/3385457.

Its possible to include it?

**Comment by jdillon** [comment]
will have a look, annoyed that --help does not show all the flags, they had a few others not shown too  that i've asked them to add in the past.

**Comment by ingokegel** [comment]
I'll add it to the help in 6.0.5. What were the other missing flags? The system properties are not documented by the --help output.

**Comment by jdillon** [comment]
@ingokegel the only recent one I know about is -J but I mentioned that to you guys already.  I'm not sure what other flags there are so I can't say, but knowing there was one before, and now is another, I'm not sure there aren't any more :-P

**Comment by jdillon** [comment]
Also added support for:
```
--disable-bundling
--incremental
```

**Comment by jdillon** [comment]
@FABH if you can give it a try and see if its working as expected, and I'll prepare a release.

@ingokegel if there are any other hidden flags please do try and update the --help output, and/or let me know if there are any that would be important to include in the maven integration.

**Comment by ingokegel** [comment]
I can't see any others, just "preserve" was missing. It was not hidden intentionally, we just forgot about it.

**Comment by jdillon** [comment]
@ingokegel thx

**Comment by FABH** [comment]
Tested the master branch and it worked!
