### ISSUE TITLE
Class DownloadFileAction moved in Install4j6

### ISSUE THREAD

**Issue by FABH** [sonatype/install4j-support#25]
Checking the class /install4j-ga/src/main/java/org/sonatype/install4j/ga/ConfigureProxyAction.java, one of it's imports was moved.
The class is DownloadFileAction and it was moved from package "com.install4j.runtime.beans.actions.update" to "com.install4j.runtime.beans.actions.net".
This change was made in version 6 of i4jruntime.jar.

**Comment by jdillon** [comment]
thx will have a look

**Comment by jdillon** [comment]
FTR I've not forgotten about this, just been very busy with other things, I hope to sort out a solution to supporting this in the near future.  Though I think it could mean we have to move to 1.1 with this incompatibility and have 1.1 require v6

**Comment by jdillon** [comment]
Updated version to 1.1.0-SNAPSHOT, fixed bug above, moves 1.1.x to require install4j v6

https://github.com/sonatype/install4j-support/commit/8957220ebde84fbe2d25b131cceb400610277ae0

**Comment by FABH** [comment]
Thanks @jdillon :)
