### ISSUE TITLE
Plugin should fail when files are missing

### ISSUE THREAD

**Issue by jschneider** [sonatype/install4j-support#29]
I moved some files in our project that resulted only in warnings from Install4j:

[INFO] Creating media file 'Windows 32bit':
[INFO]   Created media file output directory /home/johannes/projects/service/...
[INFO]   
[INFO]   Collecting files:
[INFO]       [WARNING] The path "../wibu/CodeMeterRuntime.exe" does not exist.
[INFO]       [WARNING] The path "../wibu/WibuVm.jar" does not exist.
[INFO]       [WARNING] The path "../wibu/WibuXpm4J32.dll" does not exist.
[INFO]       [WARNING] The path "../wibu/WibuXpm4J64.dll" does not exist.

I really would like to fail the build, if these files could not be found. Any idea how to solve this?
I tried "<failIfMissing>true</failIfMissing>" - but unfortunately without any effect.

**Comment by ingokegel** [comment]
This is not directly related to the maven plugin.

In install4j there is an option on the "Files->File Options" step that is called "What to do when files are missing at build time. You can set that to "Raise an error and abort".

**Comment by jschneider** [comment]
Thanks.
