### ISSUE TITLE
Update command line parameters for install4j 8.x

### ISSUE THREAD

**Issue by ingokegel** [sonatype/install4j-support#36]
The missing command line parameters are

--apple-id
--apple-id-password
--disable-bundling

**Comment by ingokegel** [comment]
Hi Jason,

Any change of making a release? I have many requests for it and I would prefer not to fork it.

Thanks!

Ingo

**Comment by jdillon** [comment]
@ingokegel sorry, I got distracted and then forgot... will put it back on my list of things to do shortly.

**Comment by tomasfrtala** [comment]
@jdillon have you time estimation when it will be available in https://mvnrepository.com/artifact/org.sonatype.install4j/install4j-maven-plugin?

**Comment by jdillon** [comment]
https://repo1.maven.org/maven2/org/sonatype/install4j/install4j-maven-plugin/1.1.2/ is released, sorry for the delay.

@ingokegel I may ping you later about longer-term strategy for maintaining this integration, but I need to check with a few folks first.

**Comment by tomasfrtala** [comment]
Thank you @jdillon I confirm everything is working right now with the new version.

**Comment by ingokegel** [comment]
Thanks a lot @jdillon, would it be possible to update the web site as well?

**Comment by jdillon** [comment]
@ingokegel site has been updated; was a bit of a PITA with the maven-site-plugin and friends not behaving; may replace all this with a new site system if I get time, but for now its updated.
